### ISSUE TITLE
IE7 star syntax gets broken

### ISSUE THREAD

**Issue by RReverser** [tdewolff/minify#137]
I'm almost feeling bad for reporting an issue related to such extremely outdated browser, but apparently, these hacks are still popular as part of various frameworks that can get broken when minified using this tool.

Basically, there are popular hacks for old IE versions that are often used to override certain properties only for them (described in e.g. https://learntech.imsu.ox.ac.uk/blog/?p=494).

Example:

```css
p {
  color: red;    /* all browsers */
  *color: blue;  /* IE7 and below */
  _color: green; /* IE6 and below */
}
```

As we can see, after minification the `_` hacks gets treated correctly, but `*` one breaks CSS:

```css
p{color:red*color:blue;_color:green}
```

Moreover, if `*` was coming as the last property and wasn't followed by a semicolon

```css
p {
  color: red;
  *color: blue
}

div {
  color: green;
}
```

it breaks the following ruleset as well:

```css
p{color:red*color:bluediv;color:green}
```

**Comment by RReverser** [comment]
@tdewolff Really not sure if this should be somehow fixed on side of parser or minifier :/ Are you familiar with CSS spec well enough to figure how modern browsers ignore that `*` without breaking everything afterwards?

**Comment by tdewolff** [comment]
Yes, it was a regression from a previous attempt to properly handle parsing errors. See https://www.w3.org/TR/css-syntax-3/#error-handling

**Comment by RReverser** [comment]
@tdewolff Thanks!

**Comment by RReverser** [comment]
FWIW tests failed on Travis (although for some reason badge shows "build passing"): https://travis-ci.org/tdewolff/minify

**Comment by RReverser** [comment]
```
--- FAIL: TestCSS (0.00s)
	css_test.go:57: 
		   given: .clearfix { *zoom: 1px; }
		  output: .clearfix{*zoom:1px;}
		expected: .clearfix{*zoom:1px}
```

**Comment by RReverser** [comment]
Btw, this from original report:

```css
p {
  color: red;    /* all browsers */
  *color: blue;  /* IE7 and below */
  _color: green; /* IE6 and below */
}
```

minifies to this now:

```css
p{color:red*color:blue;;_color:green}
```

So there is still no semicolon before `*` but instead another one appeared after the property.

**Comment by RReverser** [comment]
The second example also minifies incorrectly:

```css
p {
  color: red;
  *color: blue
}

div {
  color: green;
}
```

to

```css
p{color:red*color:blue}}div{color:green}
```

@tdewolff Can you please reopen the issue and include given examples as regression tests?
