### ISSUE TITLE
Problem in JS Minify

### ISSUE THREAD

**Issue by jinliming2** [tdewolff/minify#148]
When I use this tool to minify the JS file, I found that the tool doesn't remove the multi-line comments that are guided by `/*!`.
For example:
```javascript
/*! Hello World */
/* Hi! */
/*! This is
 Multiline
 Comment */
/* This is another
 Multiline
 Comment */
const code = 'My Code.';  // Single line
```
And I got this:
```javascript
/*!Hello World*//*!This is
Multiline
Comment*/const code='My Code.';
```
Is this intentional or unintentional? If it is intentional, can I got an option to disable it?

**Comment by jinliming2** [comment]
Same problem when minify CSS file:
```css
/*! Hello World */
/* Hi! */
/*! This is
 Multiline
 Comment */
/* This is another
 Multiline
 Comment */
.a {
  color: #f00;
}
```
Got this:
```css
/*!Hello World*//*!This is
Multiline
Comment*/.a{color:red}
```
