### ISSUE TITLE
CSS minification messes up descendant selectors

### ISSUE THREAD

**Issue by robotvert** [tdewolff/minify#16]
Basically I'm using purecss in a project and I need to redefine the font family as [this section of their doc explains](http://purecss.io/grids/#using-grids-with-custom-fonts).

The issue is that this
```css
html, button, input, select, textarea, .pure-g [class*="pure-u"] {
  font-family: 'Fira Sans', 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; 
}
```
gets turned to that
```css
html,button,input,select,textarea,.pure-g[class*=pure-u]{font-family:fira sans,helvetica neue,helvetica,arial,'sans-serif'}
```

And in the CSS world `.pure-g[class*=pure-u]` is _not_ the same as `.pure-g  [class*=pure-u]`.
