### ISSUE TITLE
CSS Variables are broken in de minifying process

### ISSUE THREAD

**Issue by Allendar** [tdewolff/minify#163]
Say I have this CSS:

```css
:root {
    --bg: #05121b;
    --clr: #dce6fb;
}

body {
    font-family: "open sans", "Helvetica Neue", Helvetica;
    font-size: 13px;
    background: var(--bg);
    color: var(--clr);
}
```

It probably doesn't get the first block, so it kills it strangely, like so:

```css
:root {
    --bg--clr
}
```

Can these more exotic notations be added to the parser so it doesn't break it?
