### ISSUE TITLE
Regression: `border: 0px somestyle somecolor` is transformed into `border: 0`

### ISSUE THREAD

**Issue by RReverser** [tdewolff/minify#203]
Ironically, CSS refactor PR (https://github.com/tdewolff/minify/pull/177) that fixed one `border` issue fixing one `border` related issue (https://github.com/tdewolff/minify/issues/176) seems to have created another obscure `border` issue.

Now CSS that looks like

```css
.x {
  border: 0px dashed red;
}
```

is minified into

```css
.x{border:0}
```

This transformation is incorrect as it doesn't take into account whether other values being removed actually correspond to their defaults from the spec. In some cases this results in break of cascading behaviour when such stylesheet is combined with another:

```css
.x {
  border-width: 1px;
}
```

Previously, combination of these would result in equivalent of `border: 1px dashed red`, but after minification `border-style` remains `none` and border doesn't appear.
