### ISSUE TITLE
Syntax error in CSS declaration breaks entire CSS

### ISSUE THREAD

**Issue by RReverser** [tdewolff/minify#206]
Currently syntax errors at the end of CSS declaration block consume the closing brace and break all the subsequent CSS.

Example input:
```css
.foo {
  baddecl
}

.bar {
  height: 100%;
}
```

Output:
```css
.foo{baddecl;.bar{height:100%}
```
