### ISSUE TITLE
border style "none" minified incorrectly to "0"

### ISSUE THREAD

**Issue by simon-says** [tdewolff/minify#214]
When used as a value in the `border` or `border-top` (and bottom/left/right) properties, the border style value of "none" is incorrectly minified to "0". 

However, when declaring a `border-style` this is not  the case.

Example from https://go.tacodewolff.nl/minify

Unminified:

```
.test-border-style { 
    border-left: 3px none red;
    border: 3px none red;
    border-style: none; 
}
```

Minified:

```
.test-border-style{border-left:3px 0 red;border:3px 0 red;border-style:none}
```

**Comment by tdewolff** [comment]
You are right, the `border` property was next in line for improvement.

Additionally, I've noticed we can't ever change `none` to `0`, like so many minifiers do. See the example below that uses default values in `border` to set the width. Both give different results:

``` css
.a {
    border: none;
    border-style: dashed;
}

.b {
    border: 0;
    border-style: dashed;
}
```
