### ISSUE TITLE
Apple Pay styling should not be treated as color

### ISSUE THREAD

**Issue by RReverser** [tdewolff/minify#217]
Safari has special vendored CSS properties for Apple Pay button styling: https://developer.apple.com/documentation/apple_pay_on_the_web/displaying_apple_pay_buttons

As seen from the docs, one of these properties might look like following:

```css
    .apple-pay-button-black {
        -apple-pay-button-style: black;
    }
    .apple-pay-button-white {
        -apple-pay-button-style: white;
    }
    .apple-pay-button-white-with-line {
        -apple-pay-button-style: white-outline;
    }
```

Currently minifier assumes that `black` and `white` are regular CSS colors, no matter what property they're in, and minifies them to `#000` and `#fff` correspondingly, which break styling, as for Safari these are expected to be regular names.

This could be treated as a browser-specific quirks and disabled just for that particular property, but blacklisting doesn't like a very failproof solution, since there are other contexts where regular identifiers might potentially have name collisions with colors, but shouldn't be treated as such.
