### ISSUE TITLE
Regression: HSLA colors get stripped with KeepCSS2

### ISSUE THREAD

**Issue by RReverser** [tdewolff/minify#218]
With `KeepCSS2`

```css
.x {
  color: hsla(5,0%,10%,0.75);
}
```

gets minified to invalid syntax

```css
.x{color:}
```

Seems related to recent changes in https://github.com/tdewolff/minify/commit/f371663f90c916521894d67638fb9401ba8c46ea
