### ISSUE TITLE
Bloats and Mangles SVGs in Data URIs

### ISSUE THREAD

**Issue by jhabdas** [tdewolff/minify#243]
Consider the following style rule I use to style external links:

```css
a[rel*="external"]::after {
  content: " " url("data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20class='i-external'%20viewBox='0%200%2032%2032'%20width='14'%20height='14'%20fill='none'%20stroke='%23ff9800'%20stroke-linecap='round'%20stroke-linejoin='round'%20stroke-width='9.38%'%3E%3Cpath%20d='M14%209%20L3%209%203%2029%2023%2029%2023%2018%20M18%204%20L28%204%2028%2014%20M28%204%20L14%2018'/%3E%3C/svg%3E");
}
```

That's an optimized SVG already. It doesn't get much smaller than that.

Now run that code through the [online minifier tool](https://go.tacodewolff.nl/minify) and notice...

<img width="647" alt="screen shot 2019-02-06 at 9 21 03 pm" src="https://user-images.githubusercontent.com/440298/52344215-26059e80-2a55-11e9-8f3e-393897ded113.png">

The output is larger than the input. Okay, that seems strange for a minification tool but I get that not everyone is using [optimized SVGs in Data URIs](https://codepen.io/tigt/post/optimizing-svgs-in-data-uris) yet.

But that's not the problem. The problem is that the tool under default settings (AFAIK) mangles the image by trying to base64 encode it. You can't do that with SVGs because they may be styled as part of the cascade.
