### ISSUE TITLE
Whitespace removed in CSS properties in unknown @rules

### ISSUE THREAD

**Issue by jansorg** [tdewolff/minify#262]
I'm writing CSS for printing with Prince XML (via hugo). The CSS formats the footnote area, https://www.princexml.com/doc-prince/#footnotes-styling .

Now 
```css
div {
  border: 1px solid black;
}

@page {
  @footnotes {
    border: 1px solid black;
  }
}
```

becomes this (tested with https://go.tacodewolff.nl/minify): 
```css
div{border:1px solid #000}@page{@footnotes{border:1pxsolidblack;}}
```

The whitespace of the border root is removed and thus breaks the printing styles.
It would be great if whitespace within unknown rules could be preserved (if that's the issue here).
