### ISSUE TITLE
CSS / AMP: Bug with minification an amp-boilerplate

### ISSUE THREAD

**Issue by pperzyna** [tdewolff/minify#300]
I believe I am using your library via Hugo. I found following error during a minification a CSS.

Un-minified:
```css
body {
	-webkit-animation: -amp-start 8s steps(1,end) 0s 1 normal both;
	-moz-animation: -amp-start 8s steps(1,end) 0s 1 normal both;
	-ms-animation: -amp-start 8s steps(1,end) 0s 1 normal both;
	animation: -amp-start 8s steps(1,end) 0s 1 normal both
}
```

Minified:

```css
body{-webkit-animation:-amp-start 8s steps(1,end)0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end)0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end)0s 1 normal both;animation:-amp-start 8s steps(1,end)0s 1 normal both}
```

and the issue is here `steps(1,end)0s`
