### ISSUE TITLE
Can't automate download of latest release

### ISSUE THREAD

**Issue by EthraZa** [tdewolff/minify#316]
Hi.
Since the releases have a version number in the file name, I can't automatically download the latest release. Please consider remove the version number from the file names.
And, since minify is Go and distributed as a single file, if possible, please consider add to the download section, a version of the binary without tgz.

**Example**:
To download today, the link is:
[https://github.com/tdewolff/minify/releases/latest/download/minify_2.7.7_linux_amd64.tar.gz](https://github.com/tdewolff/minify/releases/latest/download/minify_2.7.7_linux_amd64.tar.gz)

To be able to download without knowing the version in advance, it could be like:
[https://github.com/tdewolff/minify/releases/latest/download/minify_linux_amd64.tar.gz](https://github.com/tdewolff/minify/releases/latest/download/minify_linux_amd64.tar.gz)

To be able to download without knowing the version in advance and without the need to untar, it could be like:
[https://github.com/tdewolff/minify/releases/latest/download/minify_linux_amd64](https://github.com/tdewolff/minify/releases/latest/download/minify_linux_amd64)

**GitHub Docs**:
[Linking to releases](https://docs.github.com/en/github/administering-a-repository/linking-to-releases)

**Motivation**:
It would be nice to be able to always download and install the latest version of this wonderful tool to my Flatcar Linux (CoreOS) using the ignition setup as in:
```
files:
    - path: /opt/bin/minify
          filesystem: root
          mode: 0755
          contents:
            remote:
              url: https://github.com/tdewolff/minify/releases/latest/download/minify_linux_amd64
```
Ignition just allow me to download the file to a path and use it as is or gunzip using the flag "compression: gzip", no untar provided.
I could create a script to untar it at first boot, but I would still need to be able to download without knowing the version number to get the latest and greatest.

Thank you.
