### ISSUE TITLE
unicode-range could be minified

### ISSUE THREAD

**Issue by JRaspass** [tdewolff/minify#321]
In order to correctly serve an emoji font only when an emoji is present on a page and to override whatever glyphs exists in the body font (like that horrid b/w teacup) I use the following css:
```css
@font-face {
    font-family: emoji;
    src: local('Apple Color Emoji'),
         local('Noto Color Emoji'),
         local('Segoe UI Emoji'),
         local('Twemoji Mozilla'),
         url(/twemoji.woff2);
    unicode-range: U+2300-23FF,   /* Miscellaneous Technical */
                   U+2600-26FF,   /* Miscellaneous Symbols */
                   U+2700-27BF,   /* Dingbats */
                   U+2B00-2BFF,   /* Miscellaneous Symbols and Arrows */
                   U+1F1E6-1F1FF, /* Regional Indicator Symbols */
                   U+1F300-1F5FF, /* Miscellaneous Symbols and Pictographs */
                   U+1F600-1F64F, /* Emoticons */
                   U+1F680-1F6FF, /* Transport and Map Symbols */
                   U+1F900-1F9FF; /* Supplemental Symbols and Pictographs */
}

body { font: 16px emoji, font, system-ui, -apple-system, sans-serif }
```
The last property currently minifies to the following:
```css
unicode-range:U+2300-23FF,U+2600-26FF,U+2700-27BF,U+2B00-2BFF,U+1F1E6-1F1FF,U+1F300-1F5FF,U+1F600-1F64F,U+1F680-1F6FF,U+1F900-1F9FF
```
Based on reading https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range I think we could be smarter. Adjacent ranges could be collapse, so `U+2600-26FF,U+2700-27BF` → `U+2600-27BF` and ranges with common start and end digits could be rewritten to use wildcards, so `U+2300-23FF` → `U+23??`

What do you think? I like keeping the source code explicit with the names of each range since "emojs" as a concept are so spread out and keep getting added to, in an ideal world we'd have something like https://github.com/w3c/csswg-drafts/issues/4573 but alas not yet.
