### ISSUE TITLE
Bug: css * operator causes issues

### ISSUE THREAD

**Issue by milan60** [tdewolff/minify#424]
This piece of code
```css
* {
    box-sizing: border-box;
}
```

Causes the following error
```
unexpected * in expression on line 1 and column 1
    1: * {
       ^
```
