### ISSUE TITLE
CSS: Breaking Tailwind/Windi styling

### ISSUE THREAD

**Issue by Hrishikesh-K** [tdewolff/minify#470]
Hi,

I'm using Hugo which uses this minifier under-the-hood. For a long time, I was struggling to debug why some of my Tailwind/Windi styling was not working in Chrome. For example, the CSS filters didn't work. Upon investigation, I found out that, the following style (an example, but any style using the following format) was getting compressed:

```css
* {
  --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/);
}
```

to:

```css
* {
  --tw-ring-inset: var(--tw-empty,);
}
```

When I disabled minification in Hugo, it started working fine as those "comments" were preserved. I think other browsers are considering this as valid and thus, the styles were being applied regardless, but Chrome refused to apply styling according to these rules.

Has anyone else experienced this?

**Comment by tdewolff** [comment]
Thanks for raising this issue. I've been trying to figure out the syntax, but according to https://drafts.csswg.org/css-variables/#using-variables it is perfectly possible to have a training comma in the `var` function call, which means the value should be empty by default. Not sure what the purpose of the comments were in the original piece of CSS.

I've tried this in the latest Firefox and Chrome and both work as expected. Can you indicate what goes wrong with Chrome in your case and what the difference with Firefox is?

**Comment by Hrishikesh-K** [comment]
Thanks for taking a look.

Now this is interesting. I tried re-building my Hugo website and it seems to be having the required styles without issues. I checked further and I'm seeing that `/*!*/ /*!*/` is not being trimmed anymore. I'm sure this was happening in the past? I tried going a few releases back, but I am still seeing that the `/*!*/` is being preserved.

However, I found an old Netlify deploy where the problem was evident:

<img width="551" alt="image" src="https://user-images.githubusercontent.com/11403551/161389657-e2e355ec-5564-4d28-a263-6c879c25ccbd.png">

As you can see, Chrome has striked off all those styles and it called them "invalid". I was kinda shocked to see this was not happening on my device right now, but I used Browserstack to use Chrome 96 in which this issue was occuring. So it appears that Chrome has fixed this by Chrome 100.

This is why, as I said, Firefox or Safari never gave me this problem, as it was probably a Chrome "bug". Since your minifier is doing stuff according to standards, I guess it's not a problem with this tool after all, and it was a Chrome bug.

Sorry for not doing this research before.

**Comment by tdewolff** [comment]
Thanks for reporting back. I'm happy to hear it has been fixed in Chrome now. With respect to the comments, do you mean that the comments are not being removed any more by the minifier? That is weird because they should be removed.

**Comment by Hrishikesh-K** [comment]
Yeah I think they should be removed too, but I tried multiple stuff like minifying in Hugo itself, using the online tool from the readme, as well as CLI and it seems to be preserved in all of that.

Looking at the releases (for CLI), it seems like the latest one was in January, but I was seeing this issue happen as recent as Feb or early March. So I'm confused myself as to why I'm seeing this discrepancy now.

**Comment by tdewolff** [comment]
Hm, something must be off because the minifier clearly strips the comments:

https://go.tacodewolff.nl/minify?q=b21pbWU9dGV4dCUyRmNzcyZjc3MtcHJlY2lzaW9uPTAmc3JjPWErJTdCJTBEJTBBKysrK2NvbG9yJTNBK3ZhcigtLXNvbWV0aGluZyUyQyUyRiohKiUyRislMkYqISolMkYpJTNCJTBEJTBBJTdE

**Comment by Hrishikesh-K** [comment]
This is really weird. I tried this:

```css
* {
  --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/);
  --tw-ring-offset-width: 0px;
  --tw-ring-offset-color: #fff;
  --tw-ring-color: rgba(59, 130, 246, 0.5);
  --tw-ring-offset-shadow: 0 0 #0000;
  --tw-ring-shadow: 0 0 #0000;
  --tw-shadow: 0 0 #0000;
  scrollbar-color: initial;
  scrollbar-width: initial;
}
```

Got this:

```css
*{--tw-ring-inset:var(--tw-empty,/*!*/ /*!*/);--tw-ring-offset-width:0px;--tw-ring-offset-color:#fff;--tw-ring-color:rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow:0 0 #0000;--tw-ring-shadow:0 0 #0000;--tw-shadow:0 0 #0000;scrollbar-color:initial;scrollbar-width:initial}
```

<img width="684" alt="image" src="https://user-images.githubusercontent.com/11403551/161398333-4a5e8772-b6d7-4b15-8a96-d72e1abb228e.png">
