### ISSUE TITLE
CSS with @layer is not well compressed

### ISSUE THREAD

**Issue by hajimehoshi** [tdewolff/minify#651]
Thank you for the nice library! I found a minor issue:

Compressing this CSS

```css
@layer foo {
    p {
        font-weight: bold;
    }
}
```

results in

```css
@layer foo{p {
        font-weight: bold;
    }
}
```
