### ISSUE TITLE
css: Whitespace between values isn't collapsed

### ISSUE THREAD

**Issue by thatguystone** [tdewolff/minify#740]
The following css isn't minified properly:

```css
:root { --v: 1px   2px }
:root { --v: a,   b,   c; }
:root { --v: a,
        b,
        c;
}
```

Got:
```css
:root{--v:1px   2px}:root{--v:a,   b,   c}:root{--v:a,
        b,
        c}
```

Expected:
```css
:root{--v:1px 2px}:root{--v:a,b,c}:root{--v:a,b,c}
```

[Playground link](https://go.tacodewolff.nl/minify?q=b21pbWU9dGV4dCUyRmNzcyZjc3MtcHJlY2lzaW9uPTAmc3JjPSUzQXJvb3QrJTdCKy0tdiUzQSsxcHgrKysycHgrJTdEJTBEJTBBJTNBcm9vdCslN0IrLS12JTNBK2ElMkMrKytiJTJDKysrYyUzQislN0QlMEQlMEElM0Fyb290KyU3QistLXYlM0ErYSUyQyUwRCUwQSsrKysrKysrYiUyQyUwRCUwQSsrKysrKysrYyUzQiUwRCUwQSU3RA==)
