### ISSUE TITLE
css: Recursively minify calc()

### ISSUE THREAD

**Issue by jvoisin** [tdewolff/minify#784]
Miniflux has css code like this:

```css
translate: -50% calc(-100% - calc(var(--padding-size) * 2) - calc(var(--border-size) * 2));
```

it's currently minimized like this:

```css
translate:-50% calc(-100% - calc(var(--padding-size) * 2) - calc(var(--border-size) * 2))
```

and could be minimized further like this:

```css
translate:-50% calc(-100%-calc(var(--padding-size)*2)-calc(var(--border-size)*2))}
```

**Comment by tdewolff** [comment]
Are you sure that is correct? I recall that the `calc` function requires spaces around the operators.

**Comment by jvoisin** [comment]
It's [a bit more subtle](https://developer.mozilla.org/en-US/docs/Web/CSS/calc#rules_and_best_practices_while_using_calc):

> The + and - operators must be surrounded by [whitespace](https://developer.mozilla.org/en-US/docs/Glossary/Whitespace). For instance, calc(50% -8px) will be parsed as "a percentage followed by a negative length" — which is an invalid expression — while calc(50% - 8px) is "a percentage followed by a subtraction operator and a length". Likewise, calc(8px + -50%) is treated as "a length followed by an addition operator and a negative percentage".
>
> The * and / operators do not require whitespace, but adding it for consistency is recommended.
> It is permitted to nest calc() functions, in which case, the inner ones are treated as simple parentheses.
> For lengths, you can't use 0 to mean 0px (or another length unit); instead, you must use the version with the unit: margin-top: calc(0px + 20px); is valid, while margin-top: calc(0 + 20px); is invalid.
> Current implementations require that for the * and / operators, one of the operands has to be unitless. For /, the right operand must be unitless. For example font-size: calc(1.25rem / 1.25) is valid but font-size: calc(1.25rem / 125%) is invalid.

**Comment by tdewolff** [comment]
Great find! In fact, since nested `calc` is treated as parenthesis, we can do even better:

```css
translate:-50% calc(-100% - (var(--padding-size)*2) - (var(--border-size)*2))}
```

And assuming operator precedence as it is in math:

```css
translate:-50% calc(-100% - var(--padding-size)*2 - var(--border-size)*2)}
```

**Comment by brycewray** [comment]
In my own Hugo-built site, running this through tdewolff/minify:

```css
    --big-img-div-width: calc(var(--container-narrower-width) + var(--big-img-div-expansion-width));
    .big-img-div:not(li *) {
      width: var(--big-img-div-width);
      left: calc(calc(var(--big-img-div-width) * -1) / 2 + 50%)
    }
```

... produces this:

```css
    --big-img-div-width: calc(var(--container-narrower-width)+var(--big-img-div-expansion-width));
    .big-img-div:not(li *) {
      width: var(--big-img-div-width);
      left: calc(calc(var(--big-img-div-width) * -1)/2 + 50%)
    }
```

... which doesn't work correctly. If I run it through the minification of Hugo's esbuild-based `css.Build` instead, the problem doesn't occur. The issue here is that this is part of the critical CSS I would prefer to include in the HTML `head` (which thus would require tdewolff/minify), rather than as a separate CSS download that's minified in `css.Build`.

I realize this is probably a very niche-ish problem, but it seems to relate to the topic being discussed here.

*[Source file for the above CSS](https://github.com/brycewray/hugo-site/blob/main/assets/css/partials/__050-global.css])*
